#frontend values
app:
  name: duniversity-deployment

replicaCount: 1

image:
  repository: shubha20/duniversity-college-portal-frontend
  tag: v1.1.0

ports:
  containerPort: 3000

#backend values
backend-app:
  name: mariadb-deployment

backend:
  replicaCount: 2
  minReadySeconds: 5
  terminationGracePeriodSeconds: 5

db-image:
  name: mariadb
  tag: 10.6