apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: college-pvc
  namespace: college-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-standard
