apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duniversity-pvc1
  namespace: college-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-standard
