apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: development-team
  namespace: shubha-ns
rules:
- apiGroup: [""]
  resources: ["pods","deployments"]
  verbs: ["get","list","watch","create","delete"]